### ISSUE TITLE
Toggling Anonymous state doesn't take effect until player mouses over the token

### ISSUE THREAD

**Issue by Zamrod** [reonZ/anonymous#10]
When you right click on a token and select toggle anonymous state with the Force Toggle Nameplate, the nameplate of the creature does not appear until a player mouses over the creature at least once. If possible, I'd like it to toggle in real time since there's no way for a player to know they need to mouse over a particular creature in order to have this appear.

Here is my environment:

![image](https://github.com/reonZ/anonymous/assets/12570777/929d898d-efd5-4778-a68e-a33a479a3f0f)

Module version: 1.4.0

**Comment by reonZ** [comment]
btw, this is a foundry bug, this update will fix it until the next foundry core update
