### ISSUE TITLE
Anonymous v1.4.3 - Breaking MidiQOL

### ISSUE THREAD

**Issue by myzar472** [reonZ/anonymous#13]
One of the recent Anonymous releases seems to break MidiQOL, specifically fast forwarding rolls. I'll be crossposting to Discord as well in case it has to be covered on that front.

The steps to reproduce this bug is to just get MidiQOL enabled and enable full automation. 

Attacking a monster should do something like this, showing what hits and what doesn't, as well as damage. It could also apply the damage.
![image](https://github.com/reonZ/anonymous/assets/9061508/48bb2af7-8c4b-4a80-8414-04c146d0f677)

However, what ends up happening instead is that the roll stops. This won't proceed any further.

![image](https://github.com/reonZ/anonymous/assets/9061508/cddcba72-8f3f-4077-9c04-98c6c09aaf57)

Settings for Anonymous are default:
![image](https://github.com/reonZ/anonymous/assets/9061508/8ad2c8ee-89e6-4d31-b184-af9c8663daa5) and I also tried different variations of settings - no change.

Disabling Anonymous 1.4.3 works around the issue and rolls function fine. I also tested v1.4.2 and it works fine as well:
![image](https://github.com/reonZ/anonymous/assets/9061508/0afab1f6-59bf-4035-b182-a6fa6049ff3a)

**Comment by reonZ** [comment]
i refactored the whole module so i may have made a mistake, you gonna have to hold my hand on how to use MidiQOL though, i never used it before.

**Comment by reonZ** [comment]
after some testing, this is getting even weirder, i literally removed all the code from the module, the module script is completely blank, but the issue still persists, the mere presence of the module breaks MidiQOL for some reason.
