### ISSUE TITLE
[Feature request] Add option to toggle-off the Toggle Anonymous State in the Token HUD

### ISSUE THREAD

**Issue by Opzehn** [reonZ/anonymous#15]
As someone who is very used to the Combat Tracker being in the bottom-right corner, and who doesn't reveal many NPCs names in general, I can sometime accidentally click the button and reveal stuff that shouldn't be revealed.

Being able to toggle-off the button in the settings so it no longer appears in the Token HUD would be really nice.

**Comment by reonZ** [comment]
I don't understand, the token HUD button only appear if you right click on the token, when you took that step, you should just be careful not to click on the reveal button, you can't really click on it accidentally otherwise
