### ISSUE TITLE
midi qol names

### ISSUE THREAD

**Issue by ANormalRaft** [reonZ/anonymous#16]
![image](https://github.com/reonZ/anonymous/assets/121328293/8204d690-34bd-4e9b-ad84-417d4faae4ba)
Latest version for both modules

I know this may be behavior that is out of the scope of the module or a bug; so came to ask if hiding the name that appears in the bottom half of a midi qol card should be a feature of the module or not. It works when a copy of the npc whose name I want to hide (Approximation Cat) attacks itself, but not when anything else attacks it (like the not-hidden Goblin). To be clear the card that is problematic is when the creature is being hit, not when it hits other things

**Comment by reonZ** [comment]
I have stopped thinking about making exception for other modules pretty fast when i started, this was a lost cause when you think how many of them exist (maintaining them especially) so i added an API for third party to use.

I know quite a few have taken upon themselves to implement it into their own modules, i dunno about this one in particular but you should see about it with them.
