### ISSUE TITLE
[Feature Request] Name visibility based on Token Name Visibility or Limited Actor Ownership

### ISSUE THREAD

**Issue by XtraButtery** [reonZ/anonymous#17]
It would be nice if Anonymous could more seamlessly integrate with some existing core features in Foundry VTT[^1].

The two suggestions I would have for a more seamless and system agnostic implementation are as follows:

## Token Name Visibility

![image](https://github.com/reonZ/anonymous/assets/35461692/94cd4fa7-8a5d-472c-931c-0049bc1d8db8)
![image](https://github.com/reonZ/anonymous/assets/35461692/9aa4dbcf-e297-4755-866b-6f8807579785)

Here you can see that despite the token's name being visible based upon the token's own configuration I am unable to see its name in the combat tracker, which doesn't make much sense as there's no reason to hide the name in one place, but not another. Especially since hovering over either the name in the tracker or the token will highlight the connection.

## Limited Item Ownership

Expanding upon the current setup which allows a player to view the names of tokens they are owners of, it would make sense if a player could see the name of a token for which they have "Limited" or "Observer" ownership 

![image](https://github.com/reonZ/anonymous/assets/35461692/97782190-473a-47ed-bd64-f447c5f8113a)
![image](https://github.com/reonZ/anonymous/assets/35461692/054d6186-5e23-4c5e-baca-d8b4c6222078)

Here you can see that despite the actor's name being visible in the Actors' tab, as well as being visible while double-clicking on the token itself (which opens the Actor's sheet)

[^1]: The screenshots I've used were made using the Dungeons and Dragons Fifth Edition, however I did some testing using other systems and I believe all functionality I've shown off are _core_ FVTT features, not unique to 5E.

**Comment by reonZ** [comment]
The reason it is that way is because it requires absolutely no setup from the GM, you activate the module and that's it, no extra work.

It even takes care of the tokens name display by turning it into "by/for Owner" instead of "to Everybody" (though it won't retroactively change already placed tokens).

So it works the opposite of what you request and i have no plan of doing it the other way around.

**Comment by XtraButtery** [comment]
Obviously it's your module and you can do what you like with it, but I feel like your approach creates far more work and setup?

As a GM I have to enable/disable token name visibility already, and have been doing so in order to make sure my players see/don't see appropriate names.

I've also given them access to several monsters and NPCs with limited access so that they can read up and remind themselves on these, which appears to be standard practice for how several of the official FVTT modules that I've seen have handled things.

At the very least being able to toggle automatic visibility for actors that have _limited_ ownership (or Observers) would massively reduce the amount of work and setup that most GMs will have to do for any game they want to run with your module.

**Comment by reonZ** [comment]
> As a GM I have to enable/disable token name visibility already, and have been doing so in order to make sure my players see/don't see appropriate names.

The module change that automatically, when you drag a token on the board, it will change its name visibility so that player don't see it.
