### ISSUE TITLE
[FEATURE] DND 5E 3.0 Compatibility 

### ISSUE THREAD

**Issue by lipehique** [reonZ/anonymous#19]
Tested compatibility with DND' 5E 3.0 (and forward) compatibility.
Foundry Version: 11
DND 3.0.1
Modules: Only Anonymous
Steps to Retrace: An actor that otherwise would have its Token Name hidden outputs to chat an attack. The name of the creature is hidden in the content of the card, but the name is still visible to players. The "Hide Card Content" feature works as intended.

![image](https://github.com/reonZ/anonymous/assets/159858551/2d66aa01-d6d6-41e6-bace-f16bff40ba69)

**Comment by reonZ** [comment]
I will look into it when i have time
