### ISSUE TITLE
Midi QoL Workflow Incompatibility

### ISSUE THREAD

**Issue by puddleimages** [reonZ/anonymous#21]
Something in your recent update seems to be changing a value in the Midi-Qol workflows to undefined. It prevents my animations from triggering and breaks the workflow.

I'm getting the following error in my console when my workflow is disrupted following an attack roll:

midi-qol |  performState | Workflow Eldritch Blast 6meo6ND2AK77A0MS Workflow Actor.KgzWHcIlWIQwbszm.Item.5iwnIiRO5yWdGpkR TypeError: api is undefined

**Comment by reonZ** [comment]
This issue was fixed in September, so you are not up to date with the module.

**Comment by puddleimages** [comment]
Well it works with [1.4.4](https://github.com/reonZ/anonymous/releases/tag/1.4.4) but not with 1.5.0 so I think you might be mistaken. Issues can pop back up for various reason. I'll stick with 1.4.4 for now. Keep it up!

**Comment by reonZ** [comment]
Can you help me reproduce the issue then ? as i am not playing d&d or using that module.

**Comment by reonZ** [comment]
i install `Midi QOL` version `11.4.14` and went into a new d&d world, created a warlock, gave ownership to a player user, logged on said user, used eldritch blast on a random ape and couldn't reproduce the error.

![image](https://github.com/reonZ/anonymous/assets/651462/bd5abf7d-1ae8-4df1-9b01-ca4e5f85227d)

**Comment by puddleimages** [comment]
I can try. I'm getting the same error in my test environment with all unnecessary modules disabled.

![image](https://github.com/reonZ/anonymous/assets/84239528/0a0dfd0e-0889-41b6-997c-bfc5074deb38)

**Comment by puddleimages** [comment]
Thank you for looking into it. It appears that that issue is more complex than I thought. There must be another interaction going on with Anonymous 1.5.0. I'll dig deeper.

**Comment by reonZ** [comment]
all good then
