### ISSUE TITLE
REQUEST: "Show Name to Players" affects existing tokens

### ISSUE THREAD

**Issue by pesky-wobbit** [reonZ/anonymous#23]
Show Name to Player currently only affects new tokens.
To alter existing tokens I must manually click each token in the hud or combat tracker. 
Would be great to have a single click for Show or Hide for all tokens in all scenes (or at least the current one).

Thanks!

**Comment by reonZ** [comment]
You can actually `ctrl + click` in the combat tracker to reveal the name of all the tokens from the same actor in the current combat.
I am not planning on adding any new feature to the module otherwise.

**Comment by pesky-wobbit** [comment]
Shift-Click works for me. Thanks for the mod!
