### ISSUE TITLE
Add option to drag in token and skip anonymous option

### ISSUE THREAD

**Issue by JanHoos** [reonZ/anonymous#3]
Hi! 
If I only I had your module two sessions ago so I didn't spoilt the BBEG's name... :-p I love how you implemented this and how easy it works. 

One thing that would make it even nicer to work with is the "the token mold" option of holding shift to skip the token mold settings and just use the standard name. 

Something like that would be loveley to have. That way I can set up the token from a friendly NPC the right way when I drag it to canvas. I won't have to click on the show name on that token as that would be covered by holding the "skip" button when dragging in the token. It would mean one move vs two/three. :-)

**Comment by reonZ** [comment]
So you want to be able to add a token from an actor that is normally anonymous without the anonymous state ?

I will see what i can do about it.

**Comment by reonZ** [comment]
Alright.
