### ISSUE TITLE
Compatibility with Foundry Wire

### ISSUE THREAD

**Issue by cstby** [reonZ/anonymous#4]
[Foundry Wire](https://github.com/teroparvinen/foundry-wire) is a module for lightweight roll automation and streamlining. During comabt, it displays chat messages that reference NPC names. Those names are shown to players despite Anonymous being installed.

Screenshot of combat chat messages with both modules installed:
![image](https://user-images.githubusercontent.com/45189177/206313359-12a86ffd-a0ee-481d-955e-21480ce63590.png)

**Comment by reonZ** [comment]
I can take a look.

**Comment by reonZ** [comment]
Well i installed the module but it is not working for me, i get an error right at loading, so it is gonna have to wait sorry.

**Comment by cstby** [comment]
Awesome. I'm currently advocating to that module author to provide an option to display those turn announcement chats to players. Let's also anonymize the NPC names in those messages.

**Comment by reonZ** [comment]
Then you gonna have to ask for details about the actor related to the message then, because right now, i don't have any way to tell if i should or not make the message anonymous, it is just some text message.
