### ISSUE TITLE
[Suggestion] Alt-Text on hover

### ISSUE THREAD

**Issue by M0nk3yy** [reonZ/anonymous#6]
It would be nice if the buttons in the token HUD, and combat tracker had Alt-Text that displays on hover like the below:

![image](https://user-images.githubusercontent.com/66137312/207382336-73919813-8563-4117-8032-670289e94dde.png)

And a combat tracker example:

![image](https://user-images.githubusercontent.com/66137312/207394227-921a3b06-a354-4c7f-999d-12b4e7f4b8b1.png)

**Comment by reonZ** [comment]
Tooltips for combat racker and token HUD have been added with version `1.1.3`
