### ISSUE TITLE
Toggle Anonymous

### ISSUE THREAD

**Issue by Gossetjr** [reonZ/anonymous#7]
Any chance you would be willing/interested in an option to have the Toggle Anonymous apply to all tokens of the base creature? Example being Goblin Warrior, it will toggle Anonymous setting for all the Goblin Warriors?

Just a thought, what do you think?

**Comment by reonZ** [comment]
It could be done, i could also have 2 separate toggles for all the tokens on current scene or on all scenes.
I will see what i can do.

**Comment by reonZ** [comment]
`1.2.0`
-   holding `shift` while toggling a name from the combat tracker will toggle the names of all the combatants with the same actor

This feature is only for the combat tracker, i don't intend to go further with it.
