### ISSUE TITLE
[feature request]

### ISSUE THREAD

**Issue by Orionox** [reonZ/anonymous#8]
NPC's added to the combat tracker aren't just anonymous, but hidden completely from the players. I like letting my players know their initiative, but not the monsters.

**Comment by reonZ** [comment]
Can you be a bit more explicit as to what you want ?

**Comment by Orionox** [comment]
basically, I'd like it is NPC's defaulted to "hidden" when added to the combat tracker.

**Comment by reonZ** [comment]
But anonymous is not a module about combat tracker, it just makes actors anonymous.
Also, you can already do that with core foundry by having your NPCs hidden before adding them to the tracker.
This is beyond the scope of this module, sorry.

**Comment by Orionox** [comment]
Doesn't this hide the name in the combat tracker? Also, if I hide the
creature then players can't see them.

**Comment by reonZ** [comment]
It does, but it doesn't interact with the combat in any way.

The combat tracker is just a visual representation of a combat, what you are asking is for the module to intercept and modify the combat itself, this is not what the module is made for.
