### ISSUE TITLE
Issue with a name being the same as some part of the Chat Card's data

### ISSUE THREAD

**Issue by thatlonelybugbear** [reonZ/anonymous#9]
This is more of a funny interaction with the module and Chat Cards.

For testing reasons I had named an NPC `1`.

Well 🤣 

![image](https://github.com/reonZ/anonymous/assets/7237090/8f744472-3cae-4093-9b9c-4d006b2df09d)

**Comment by thatlonelybugbear** [comment]
Actor name: Dexterity
Token name: d20

I am just reporting this, I guess noone would do that TBH :)

![image](https://github.com/reonZ/anonymous/assets/7237090/6ea7eaeb-ec22-4bd0-88f1-900437465298)

**Comment by reonZ** [comment]
That is funny indeed, while i could do something for the dice roll part (because it is core foundry), the saving throw is more system specific.
